// Copies the EXPO_PUBLIC_* lines from the repo-root .env into apps/mobile/.env (Expo only reads the project folder).
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../../../.env');
const out = path.resolve(here, '../.env');
if (!existsSync(root)) {
  console.log('[sync-env] no root .env found; the app will use sample data.');
  process.exit(0);
}
const lines = readFileSync(root, 'utf8')
  .split(/\r?\n/)
  .filter((l) => /^EXPO_PUBLIC_[A-Z0-9_]+=/.test(l));
writeFileSync(out, `# Generated by scripts/sync-env.mjs from ../../.env — do not edit\n${lines.join('\n')}\n`);
console.log(`[sync-env] wrote ${lines.length} EXPO_PUBLIC_* values to apps/mobile/.env`);
